import { STYLE_ID, RESULTS_HOST_ID } from '../constants.js';

export function injectStyles() {
  if (document.getElementById(STYLE_ID)) return;
  const style = document.createElement('style');
  style.id = STYLE_ID;
  style.textContent = `
#${RESULTS_HOST_ID}{display:block;width:100%;color:var(--spice-text,#fff);font-family:var(--encore-body-font-stack,inherit);contain:layout style}
#${RESULTS_HOST_ID}[hidden]{display:none!important}
#${RESULTS_HOST_ID} *{box-sizing:border-box}
.smart-search-native-active{box-shadow:0 0 0 1px var(--spice-button,#1ed760)!important}
.smart-search-advanced-view [data-testid="playlist-tracklist"],.smart-search-advanced-view .main-trackList-trackList,.smart-search-advanced-view [role="grid"]{display:none!important}
.ss1-shell{width:100%;padding:0 8px 18px}
.ss1-toolbar{min-height:48px;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:8px 8px 8px 12px;border-bottom:1px solid color-mix(in srgb,var(--spice-text,#fff) 10%,transparent)}
.ss1-summary{display:flex;align-items:center;gap:9px;min-width:0;color:var(--spice-subtext,#b3b3b3);font-size:13px}.ss1-summary strong{color:var(--spice-text,#fff);font-size:14px}
.ss1-smart-dot{width:8px;height:8px;border-radius:50%;background:var(--spice-button,#1ed760);box-shadow:0 0 0 3px color-mix(in srgb,var(--spice-button,#1ed760) 18%,transparent)}
.ss1-progress{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ss1-actions{display:flex;align-items:center;gap:8px;flex:0 0 auto}
.ss1-button{min-height:32px;border:0;border-radius:999px;padding:0 13px;font:inherit;font-size:13px;font-weight:700;cursor:pointer;color:var(--spice-text,#fff);background:color-mix(in srgb,var(--spice-text,#fff) 10%,transparent);display:inline-flex;align-items:center;justify-content:center;text-align:center;line-height:1.2;text-decoration:none;box-sizing:border-box}
.ss1-button:hover:not(:disabled){background:color-mix(in srgb,var(--spice-text,#fff) 17%,transparent);transform:scale(1.02)}.ss1-button:focus-visible{outline:2px solid var(--spice-text,#fff);outline-offset:2px}
.ss1-button.primary{background:var(--spice-button,#1ed760);color:#000!important}.ss1-button:disabled{opacity:.45;cursor:default;transform:none}.ss1-button.icon{width:32px;padding:0;display:grid;place-items:center}
.ss1-status{padding:18px 12px;color:var(--spice-subtext,#b3b3b3);font-size:14px}.ss1-status.error{color:#f15e6c;display:flex;align-items:flex-start;gap:12px;flex-wrap:wrap}.ss1-status.query-error{color:#f6c453}
.ss1-column-header,.ss1-row{display:grid;grid-template-columns:42px minmax(240px,2fr) minmax(170px,1fr) minmax(135px,.8fr) 64px;align-items:center;column-gap:12px}
.ss1-column-header{position:sticky;top:0;z-index:2;min-height:36px;padding:0 12px;color:var(--spice-subtext,#b3b3b3);font-size:12px;border-bottom:1px solid color-mix(in srgb,var(--spice-text,#fff) 10%,transparent);background:var(--spice-main,#121212)}
.ss1-row{position:relative;min-height:56px;padding:4px 12px;border-radius:4px;color:var(--spice-text,#fff)}.ss1-row:hover,.ss1-row:focus-within{background:color-mix(in srgb,var(--spice-text,#fff) 9%,transparent)}.ss1-row.is-playing .ss1-title{color:var(--spice-button,#1ed760)}
.ss1-row-number{position:relative;text-align:right;color:var(--spice-subtext,#b3b3b3);font-variant-numeric:tabular-nums;min-height:40px;display:flex;align-items:center;justify-content:flex-end}
.ss1-row-play{position:absolute;right:-5px;top:50%;translate:0 -50%;display:none;width:36px;height:36px;padding:0;border:0;border-radius:50%;background:transparent;color:var(--spice-text,#fff);cursor:pointer;align-items:center;justify-content:center}.ss1-row-play svg{width:20px;height:20px;display:block;fill:currentColor}.ss1-row-play:hover{background:color-mix(in srgb,var(--spice-text,#fff) 10%,transparent)}
.ss1-row:hover .ss1-row-index,.ss1-row:focus-within .ss1-row-index{visibility:hidden}.ss1-row:hover .ss1-row-play,.ss1-row:focus-within .ss1-row-play{display:flex}
.ss1-title-cell{display:flex;align-items:center;gap:12px;min-width:0}.ss1-cover,.ss1-cover-placeholder{width:40px;height:40px;border-radius:4px;background:#282828;flex:0 0 auto}.ss1-cover{object-fit:cover}.ss1-title-stack,.ss1-title,.ss1-artists,.ss1-album,.ss1-added{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ss1-title{font-size:14px}.ss1-artists,.ss1-album,.ss1-added,.ss1-duration{font-size:12px;color:var(--spice-subtext,#b3b3b3)}.ss1-duration{text-align:right;font-variant-numeric:tabular-nums}.ss1-sentinel{height:1px}
.ss1-collapsed-note{padding:14px 12px;color:var(--spice-subtext,#b3b3b3);font-size:12px}

.ss1-syntax-assist{position:fixed;z-index:100000;max-height:min(360px,45vh);overflow:auto;border-radius:20px;background:color-mix(in srgb,var(--spice-main,#121212) 96%,#fff 4%);border:1px solid color-mix(in srgb,var(--spice-text,#fff) 11%,transparent);box-shadow:0 18px 54px rgba(0,0,0,.45);padding:8px;font-family:var(--encore-body-font-stack,inherit);color:var(--spice-text,#fff);box-sizing:border-box;backdrop-filter:blur(18px)}
.ss1-syntax-assist[hidden]{display:none!important}.ss1-syntax-assist-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:8px 10px 7px}.ss1-syntax-assist-head strong{font-size:12px}.ss1-syntax-assist-head span{font-size:11px;color:var(--spice-subtext,#b3b3b3)}
.ss1-syntax-assist-list{display:grid;gap:4px}.ss1-syntax-assist-item{width:100%;min-height:42px;border:0;border-radius:14px;padding:8px 11px;background:transparent;color:var(--spice-text,#fff);display:flex;align-items:center;justify-content:space-between;gap:14px;text-align:left;cursor:pointer;font:inherit}.ss1-syntax-assist-item:hover,.ss1-syntax-assist-item:focus-visible{background:color-mix(in srgb,var(--spice-text,#fff) 9%,transparent);outline:none}.ss1-syntax-assist-item code{font:600 12px/1.2 ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--spice-text,#fff)}.ss1-syntax-assist-item span{font-size:11px;color:var(--spice-subtext,#b3b3b3);white-space:nowrap}

.ss1-settings{width:100%;max-width:100%;min-width:0;box-sizing:border-box;overflow-x:hidden;color:var(--spice-text,#fff)}.ss1-settings-row{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:14px 0;border-bottom:1px solid color-mix(in srgb,var(--spice-text,#fff) 10%,transparent)}.ss1-settings-copy{min-width:0;overflow-wrap:anywhere}.ss1-settings-title{font-weight:700}.ss1-settings-desc{margin-top:3px;color:var(--spice-subtext,#b3b3b3);font-size:12px;line-height:1.4}
.ss1-toggle{min-width:48px;height:28px;border:0;border-radius:999px;padding:3px;background:#535353;cursor:pointer;position:relative;flex:0 0 auto}.ss1-toggle::after{content:'';position:absolute;top:4px;left:4px;width:20px;height:20px;border-radius:50%;background:#fff;transition:transform 120ms ease}.ss1-toggle[aria-pressed='true']{background:var(--spice-button,#1ed760)}.ss1-toggle[aria-pressed='true']::after{transform:translateX(20px)}
.ss1-panel{margin-top:18px;padding:14px;border-radius:10px;background:color-mix(in srgb,var(--spice-text,#fff) 6%,transparent);border:1px solid color-mix(in srgb,var(--spice-text,#fff) 7%,transparent)}.ss1-panel-title{font-weight:700;margin-bottom:7px}.ss1-panel-desc,.ss1-muted{color:var(--spice-subtext,#b3b3b3);font-size:12px;line-height:1.5}.ss1-collapsible{padding:0}.ss1-panel-summary{list-style:none;display:flex;align-items:center;justify-content:space-between;gap:16px;cursor:pointer;padding:14px;user-select:none}.ss1-panel-summary::-webkit-details-marker{display:none}.ss1-panel-summary .ss1-panel-title{margin:0}.ss1-panel-chevron{color:var(--spice-subtext,#b3b3b3);font-size:18px;transition:transform 120ms ease}.ss1-collapsible[open] .ss1-panel-chevron{transform:rotate(180deg)}.ss1-panel-body{padding:0 14px 14px;border-top:1px solid color-mix(in srgb,var(--spice-text,#fff) 8%,transparent)}.ss1-tutorial-grid{display:grid;grid-template-columns:minmax(150px,auto) 1fr;gap:10px 18px;margin-top:14px;align-items:start;font-size:12px}.ss1-tutorial-grid>code{color:var(--spice-text,#fff);white-space:nowrap;font-weight:700}.ss1-tutorial-meaning{display:flex;gap:7px;min-width:0}.ss1-tutorial-meaning strong{min-width:96px}.ss1-tutorial-meaning span{color:var(--spice-subtext,#b3b3b3)}
.ss1-diag-grid{display:grid;grid-template-columns:minmax(150px,1fr) auto;gap:7px 14px;font-size:12px;margin-top:12px}.ss1-diag-ok{color:var(--spice-button,#1ed760)}.ss1-diag-bad{color:#f6c453}.ss1-diag-neutral{color:var(--spice-subtext,#b3b3b3)}.ss1-panel-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.ss1-action-feedback{margin-top:10px;padding:8px 10px;border-radius:7px;background:color-mix(in srgb,var(--spice-text,#fff) 6%,transparent);font-size:12px;line-height:1.4;color:var(--spice-subtext,#b3b3b3)}.ss1-feedback-ok{color:var(--spice-button,#1ed760)}.ss1-feedback-warn{color:#f6c453}.ss1-feedback-error{color:#f15e6c}.ss1-pre{margin-top:10px;padding:10px;border-radius:6px;background:rgba(0,0,0,.25);font:11px/1.45 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;max-height:220px;overflow:auto}.ss1-version{margin-top:16px;color:var(--spice-subtext,#b3b3b3);font-size:11px}

.ss1-release-overlay{position:fixed;inset:0;z-index:2147483000;display:grid;place-items:center;padding:var(--ss1-release-overlay-pad,24px);background:rgba(0,0,0,.62);backdrop-filter:blur(3px);box-sizing:border-box}
.ss1-release-dialog{width:var(--ss1-release-dialog-width,min(68vw,1800px));max-width:100%;max-height:var(--ss1-release-dialog-max-height,calc(100vh - 48px));display:flex;flex-direction:column;min-width:0;margin:0;border-radius:32px;overflow:hidden;background:var(--spice-main,#121212);border:1px solid color-mix(in srgb,var(--spice-text,#fff) 8%,transparent);box-shadow:0 28px 96px rgba(0,0,0,.56);color:var(--spice-text,#fff);font-family:var(--encore-body-font-stack,inherit)}
.ss1-release-topbar{min-height:68px;display:flex;align-items:center;justify-content:space-between;gap:18px;padding:0 clamp(20px,2vw,30px);border-bottom:1px solid color-mix(in srgb,var(--spice-text,#fff) 9%,transparent);flex:0 0 auto}.ss1-release-topbar strong{font-size:17px;font-weight:800;letter-spacing:-.015em}.ss1-release-close{width:38px;height:38px;border:0;border-radius:50%;display:grid;place-items:center;background:transparent;color:var(--spice-subtext,#b3b3b3);font:300 28px/1 var(--encore-body-font-stack,inherit);cursor:pointer}.ss1-release-close:hover,.ss1-release-close:focus-visible{background:color-mix(in srgb,var(--spice-text,#fff) 9%,transparent);color:var(--spice-text,#fff);outline:none}
.ss1-release-notes{min-width:0;color:var(--spice-text,#fff);padding:clamp(20px,2vw,34px);background:var(--spice-main,#121212);font-family:var(--encore-body-font-stack,inherit);overflow:auto;overscroll-behavior:contain;flex:1 1 auto}
.ss1-release-hero{display:flex;align-items:center;gap:clamp(16px,1.8vw,24px);padding:0 2px clamp(18px,2vw,24px)}.ss1-release-app-icon{width:68px;height:68px;border-radius:23px;display:grid;place-items:center;flex:0 0 auto;background:color-mix(in srgb,var(--spice-button,#1ed760) 90%,#fff);color:#06240f;font-size:28px;font-weight:900;box-shadow:0 10px 34px rgba(0,0,0,.28)}.ss1-release-hero-copy{min-width:0;flex:1}.ss1-release-overline{font-size:10.5px;line-height:1.2;letter-spacing:.13em;font-weight:850;color:var(--spice-button,#1ed760)}.ss1-release-heading{margin-top:5px;font-size:clamp(26px,2.4vw,38px);line-height:1.05;font-weight:820;letter-spacing:-.04em}.ss1-release-subtitle{margin-top:8px;color:var(--spice-subtext,#b3b3b3);font-size:13px;line-height:1.45}.ss1-release-version-chip{display:inline-flex;align-items:center;margin-top:11px;min-height:28px;padding:0 11px;border-radius:999px;background:color-mix(in srgb,var(--spice-button,#1ed760) 14%,transparent);color:var(--spice-button,#1ed760);font-size:11px;font-weight:800}
.ss1-release-sections{display:grid;grid-template-columns:1fr;gap:11px}.ss1-release-section{padding:16px 20px;border-radius:22px;background:color-mix(in srgb,var(--spice-text,#fff) 5%,transparent);border:1px solid color-mix(in srgb,var(--spice-text,#fff) 7%,transparent)}.ss1-release-section-header{display:flex;align-items:center;gap:10px;font-size:14px}.ss1-release-section-icon{width:32px;height:32px;border-radius:11px;display:grid;place-items:center;background:color-mix(in srgb,var(--spice-text,#fff) 8%,transparent);font-size:13px;font-weight:900}.ss1-release-section-fixed .ss1-release-section-icon{background:color-mix(in srgb,#78d993 16%,transparent);color:#78d993}.ss1-release-section-improved .ss1-release-section-icon{background:color-mix(in srgb,#8ab4f8 16%,transparent);color:#8ab4f8}.ss1-release-section-new .ss1-release-section-icon{background:color-mix(in srgb,#c6a7ff 16%,transparent);color:#c6a7ff}.ss1-release-section-list{margin:10px 0 0;padding-left:20px;color:var(--spice-subtext,#b3b3b3);font-size:13px;line-height:1.45;max-width:none}.ss1-release-section-list li+li{margin-top:4px}.ss1-release-section-list li::marker{color:color-mix(in srgb,var(--spice-text,#fff) 45%,transparent)}
.ss1-release-footer{display:grid;grid-template-columns:minmax(0,1fr) minmax(130px,180px);gap:12px;align-items:stretch;margin-top:16px}.ss1-release-links{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin:0}.ss1-release-link{min-height:44px;padding:0 14px;border-radius:999px;display:inline-flex;align-items:center;justify-content:center;gap:8px;text-decoration:none;text-align:center;color:var(--spice-text,#fff);background:color-mix(in srgb,var(--spice-text,#fff) 8%,transparent);font-size:12.5px;font-weight:760;line-height:1;box-sizing:border-box;transition:background-color 120ms ease,transform 90ms ease}.ss1-release-link:hover{background:color-mix(in srgb,var(--spice-text,#fff) 13%,transparent);transform:translateY(-1px)}.ss1-release-link-icon{width:21px;height:21px;border-radius:50%;display:grid;place-items:center;background:color-mix(in srgb,var(--spice-text,#fff) 8%,transparent);font-size:11px;font-weight:900}.ss1-release-done{width:100%;min-height:44px;margin:0;border:0;border-radius:999px;background:var(--spice-button,#1ed760);color:#071b0d!important;font:inherit;font-size:13.5px;font-weight:850;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:filter 120ms ease,transform 90ms ease}.ss1-release-done:hover{filter:brightness(1.06);transform:translateY(-1px)}.ss1-release-done:active{transform:scale(.99)}.ss1-release-link:focus-visible,.ss1-release-done:focus-visible{outline:2px solid var(--spice-text,#fff);outline-offset:2px}
@media(max-width:700px){.ss1-release-overlay{padding:12px}.ss1-release-dialog{border-radius:24px}.ss1-release-topbar{min-height:58px;padding:0 16px}.ss1-release-notes{padding:16px}.ss1-release-hero{align-items:flex-start;gap:13px}.ss1-release-app-icon{width:52px;height:52px;border-radius:17px}.ss1-release-heading{font-size:25px}.ss1-release-section{padding:15px;border-radius:20px}.ss1-release-footer{grid-template-columns:1fr}.ss1-release-links{grid-template-columns:1fr}.ss1-release-done{min-height:48px}}
@media(max-width:760px){.ss1-tutorial-grid{grid-template-columns:1fr}.ss1-tutorial-meaning{display:block}.ss1-tutorial-meaning strong{display:block;margin-bottom:2px}.ss1-syntax-assist{max-width:calc(100vw - 24px)}}
@media(max-width:1000px){.ss1-column-header,.ss1-row{grid-template-columns:38px minmax(220px,2fr) minmax(150px,1fr) 60px}.ss1-date-column{display:none}}
@media(max-width:760px){.ss1-toolbar{align-items:flex-start;flex-direction:column}.ss1-actions{width:100%;justify-content:flex-end}.ss1-column-header,.ss1-row{grid-template-columns:34px minmax(180px,1fr) 56px}.ss1-album-column,.ss1-date-column{display:none}.ss1-shell{padding-left:0;padding-right:0}}
`;
  document.head.appendChild(style);
}
