export const state = {
  S: null,
  playlistId: null,
  tracks: [],
  filtered: [],
  query: '',
  queryAst: { kind: 'true' },
  queryErrors: [],
  loading: false,
  loadingPlaylistId: null,
  lastError: null,
  source: null,
  cache: new Map(),
  hiddenTracklist: null,
  hiddenTracklistDisplay: '',
  nativeSearchInput: null,
  nativeSearchListener: null,
  nativeSearchMissingSince: 0,
  resultsHost: null,
  resultsList: null,
  resultsSentinel: null,
  resultsObserver: null,
  renderedCount: 0,
  playbackSession: null,
  playbackMaintenanceInFlight: false,
  playbackBusy: false,
  routeGeneration: 0,
  smartRefreshPending: false,
  yearMetadataLoading: false,
  lastYearMetadataSummary: null,
  mutationWatcher: null,
  lastPlaylistFingerprint: '',
  sortState: { key: 'custom', direction: 'asc', source: 'default' },
  sortSignature: 'custom:asc',
  syntaxHelpHost: null,
};
